### PR TITLE
ensure we finish reading stderr pipe before calling cmd.Wait()

### LINKED ISSUE #116: reading plugin stderr read |0: file already closed
I'm seeing intermittent errors being logged from go-plugin with a message of "reading plugin stderr", and an error of "read |0: file already closed".  This seems to happen when plugins are terminated.

In looking at https://golang.org/src/os/exec/exec.go?s=17633:17682#L601, and `client.go`, it seems like there may be a race condition where the reader side of the pipe is closed after the command exits, but the go-plugin client is still trying to read from it.  The client's `logStderr` is looking for an `io.EOF` error, but in this case I think it's actually getting some variant of the `os.ErrClosed` error. I'm not familiar enough with the code to understand exactly what's going on/what should be changed, though. Hope this can point someone in the right direction!

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

Fixes #116 

cc @jbardin

### CODE REVIEW

**Comment by skriss** [comment]
FYI, I let this run overnight in a daemon process and can confirm I'm no longer getting the error from #116.

**Comment by skriss** [comment]
@jbardin just pinging on this, thanks :)

**Comment by skriss** [comment]
Another ping on this @jbardin.

**Comment by jbardin** [comment]
Sorry about the delay @skriss, we've been tied up with the terraform side of things. 
I'll take care of this shortly, so we can get it in an upcoming release over there too.

**Comment by skriss** [comment]
No worries, I figured :) Thanks!

**Pull request merged**
